// <auto-generated />
using System;
using JobBoard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobBoard.Infrastructure.Migrations
{
    [DbContext(typeof(JobBoardContext))]
    [Migration("20200713214640_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobBoard.Core.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            CreatedAt = new DateTime(2020, 7, 13, 15, 46, 39, 992, DateTimeKind.Local).AddTicks(6293),
                            Description = "We are looking for a Python Web Developer responsible for managing the interchange of data between the server and the users.",
                            ExpiresAt = new DateTime(2020, 7, 28, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2106),
                            Title = "Python Developer"
                        },
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            CreatedAt = new DateTime(2020, 7, 13, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2934),
                            Description = "Architect, build and maintain excellent React Native applications with clean code.",
                            ExpiresAt = new DateTime(2020, 7, 28, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2951),
                            Title = "React Native Developer"
                        },
                        new
                        {
                            Id = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            CreatedAt = new DateTime(2020, 7, 13, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2969),
                            Description = "Our enterprise-level client is looking for a junior to mid-level Product Designer to assist with the launch of several pilots.",
                            ExpiresAt = new DateTime(2020, 7, 28, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2970),
                            Title = "UX Designer"
                        },
                        new
                        {
                            Id = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            CreatedAt = new DateTime(2020, 7, 13, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2975),
                            Description = "Analyze current technology utilized within the company and develop steps and processes to improve and expand upon them.",
                            ExpiresAt = new DateTime(2020, 7, 28, 15, 46, 39, 994, DateTimeKind.Local).AddTicks(2977),
                            Title = "DevOps engineer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
